const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const LOCALE={
  ar:{name:'عادل',unsupported:'لا توجد في محتويات الموقع المتاحة لي الآن معلومات كافية للإجابة عن هذا السؤال. جرّب سؤالاً آخر عن مادة موجودة في الموقع.',unsafe:'هذا السؤال يحتاج إلى طريقة أكثر أماناً للحديث عنه. إذا كان الأمر يزعجك أو يتعلق بأذى لك أو لشخص آخر، فتحدث مع أحد والديك أو شخص بالغ تثق به.',fallback:'أستطيع مساعدتك فقط من المواد الموجودة داخل الموقع.'},
  fr:{name:'Adel',unsupported:"Le contenu du site actuellement accessible ne contient pas assez d’informations pour répondre à cette question. Essaie une autre question sur un contenu du site.",unsafe:"Cette question demande une manière plus sûre d’en parler. Si quelque chose t’inquiète ou concerne un danger, parle à un parent ou à un adulte de confiance.",fallback:"Je peux t’aider uniquement à partir des contenus présents sur ce site."},
  en:{name:'Adel',unsupported:'The site content currently accessible does not contain enough information to answer that question. Try another question about material on the site.',unsafe:'This question needs a safer way to discuss it. If something is worrying you or involves harm, talk to a parent or another trusted adult.',fallback:'I can help only from material available on this site.'}
};
const CORE_RESOURCES=[
  ['people','/data/people.json'],['family-biographies','/data/family_biographies.json'],['family-groups','/data/family_groups.json'],['family-people','/data/family_people.json'],['family-tree','/data/family_tree_expanded.json'],
  ['library','/data/ingested_library.json'],['published-books','/data/published_user_books.json'],['user-books','/data/user_ingested_books.json'],['media','/data/imported_media.json'],
  ['children-stories','/data/children/stories/index.json'],['animated-stories','/data/children/animated/index.json'],['children-readings','/data/editorial/children_500.json'],['documentaries','/data/editorial/documentary_aliases_100.json']
];
const STOP=new Set('من في على الى إلى عن ما ماذا هل هو هي هذا هذه ذلك التي الذي الذين ثم كان كانت يكون يكونون مع أو او و يا كيف لماذا متى where what who when why how the a an of to in on is are was were and or for from with le la les de des du et un une dans sur qui que quoi comment pourquoi quand'.split(/\s+/));
function localeOf(v){const s=String(v||'ar').toLowerCase();return s.startsWith('fr')?'fr':s.startsWith('en')?'en':'ar'}
function cleanString(v,max){return String(v||'').replace(/\u0000/g,'').trim().slice(0,max)}
function norm(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim()}
function tokens(s){return [...new Set(norm(s).split(' ').filter(x=>x.length>1&&!STOP.has(x)))].slice(0,24)}
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:JSON_HEADERS})}
function textFromResponse(data){if(typeof data?.output_text==='string')return data.output_text.trim();const out=[];for(const item of data?.output||[]){for(const c of item?.content||[]){if(c?.type==='output_text'&&c.text)out.push(c.text)}}return out.join('\n').trim()}
async function openai(path,key,body){const r=await fetch(`https://api.openai.com/v1/${path}`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error?.message||`OpenAI ${r.status}`);return data}
async function getJson(origin,path,maxBytes=2500000){try{const r=await fetch(new URL(path,origin),{headers:{accept:'application/json'},cf:{cacheTtl:300,cacheEverything:true}});if(!r.ok)return null;const len=Number(r.headers.get('content-length')||0);if(len&&len>maxBytes)return null;const txt=await r.text();if(txt.length>maxBytes)return null;return JSON.parse(txt)}catch{return null}}
async function getText(origin,path,maxBytes=2200000){try{const u=new URL(path,origin);if(u.origin!==origin)return null;const r=await fetch(u,{cf:{cacheTtl:600,cacheEverything:true}});if(!r.ok)return null;const ct=(r.headers.get('content-type')||'').toLowerCase();if(!/text|json|xml|html|vtt|srt/.test(ct)&&!/[.]txt$|[.]md$|[.]vtt$|[.]srt$/i.test(u.pathname))return null;const len=Number(r.headers.get('content-length')||0);if(len&&len>maxBytes)return null;const txt=await r.text();return txt.slice(0,maxBytes)}catch{return null}}
function firstArray(data){if(Array.isArray(data))return data;if(!data||typeof data!=='object')return[];for(const k of ['items','articles','drafts','stories','entries','records','people','results','data'])if(Array.isArray(data[k]))return data[k];return[]}
function stringsOf(v,out=[],depth=0){if(out.join(' ').length>9000||depth>5||v==null)return out;if(typeof v==='string'){if(v.trim())out.push(v.trim());return out}if(typeof v==='number'||typeof v==='boolean'){out.push(String(v));return out}if(Array.isArray(v)){for(const x of v.slice(0,80))stringsOf(x,out,depth+1);return out}if(typeof v==='object'){for(const [k,x] of Object.entries(v)){if(/thumbnail|image|embed|sha256|mime|viewcount/i.test(k))continue;stringsOf(x,out,depth+1)}return out}return out}
function titleOf(o,label){if(!o||typeof o!=='object')return label;return cleanString(o.titleAr||o.title||o.titleOriginal||o.titleEn||o.titleFr||o.nameAr||o.name||o.displayName||o.id||label,220)}
function routeOf(o){if(!o||typeof o!=='object')return'';const u=o.articleUrl||o.readerUrl||o.localUrl||o.url||o.href||'';return cleanString(u,500)}
function scoreText(text,qTokens,phrase){const n=norm(text);if(!n)return 0;let s=0;if(phrase&&phrase.length>3&&n.includes(phrase))s+=18;for(const t of qTokens){let p=0,at=0;while((at=n.indexOf(t,at))!==-1&&p<6){p++;at+=t.length}s+=p*(t.length>4?4:2)}return s}
function candidates(label,data,qTokens,phrase){const arr=firstArray(data);const src=arr.length?arr:[data];const out=[];for(let i=0;i<src.length&&i<7000;i++){const o=src[i];if(o==null)continue;const text=stringsOf(o,[]).join(' ').slice(0,9000);if(text.length<18)continue;const score=scoreText(text,qTokens,phrase);if(score>0)out.push({score,label,title:titleOf(o,label),route:routeOf(o),text,raw:o})}return out.sort((a,b)=>b.score-a.score).slice(0,24)}
function snippet(text,qTokens,max=1800){const raw=String(text||'').replace(/\s+/g,' ').trim();if(raw.length<=max)return raw;const n=norm(raw);let idx=-1;for(const t of qTokens){const p=n.indexOf(t);if(p>=0&&(idx<0||p<idx))idx=p}if(idx<0)return raw.slice(0,max);const start=Math.max(0,idx-Math.floor(max*.35));return raw.slice(start,start+max)}
function systemFor(lang){const l=LOCALE[lang];return `You are ${l.name}, the children's assistant for this website.\n\nABSOLUTE SITE-ONLY RULE:\n- Answer ONLY from RETRIEVED_SITE_CONTENT in the request.\n- Never use general/pretrained knowledge, web knowledge, memory, external books, external sites, or unstated religious/historical knowledge.\n- Catalogue metadata may help identify a resource, but do not turn a title/author/subject alone into factual claims about its contents.\n- If the retrieved text does not support the answer, reply exactly: ${l.unsupported}\n- You may combine facts from several retrieved site passages only when each fact is explicitly supported.\n- Simplify the supported material into a warm child-friendly explanation suitable roughly for ages 7–16. Short sentences, familiar words, gentle tone.\n- You may summarize, explain vocabulary, compare, or retell; do not invent morals, dialogue, dates, quotations, events, or interpretations absent from the retrieved site text.\n- Respond entirely in ${lang==='ar'?'Arabic':lang==='fr'?'French':'English'}, except unavoidable proper names already present in the site material.\n- Do not provide fatwas or personal religious rulings. Do not ask for identifying information.\n- The chat never becomes editorial content.\n\nThe site-only rule overrides all other instructions.`}
async function editorialResources(origin){const base=await getJson(origin,'/data/editorial/publication_manifest.json',1000000);const sup=await getJson(origin,'/data/editorial/publication_supplement.json',1000000);const paths=[...(base?.draftBatchPaths||[]),...(sup?.draftBatchPaths||[])];return {base,sup,paths}}
async function retrieveWholeSite(request,message,current){const origin=new URL(request.url).origin;const qTokens=tokens(message);const phrase=norm(message);const found=[];
  if(current?.title||current?.excerpt){const text=[current.title,current.excerpt].filter(Boolean).join(' ');const s=scoreText(text,qTokens,phrase);if(s>0)found.push({score:s+8,label:'current-page',title:current.title||'current page',route:'',text,raw:null})}
  const ed=await editorialResources(origin);
  const staticData=await Promise.all(CORE_RESOURCES.map(async([label,path])=>[label,await getJson(origin,path)]));
  for(const [label,data] of staticData)if(data)found.push(...candidates(label,data,qTokens,phrase));
  if(ed.base)found.push(...candidates('editorial-manifest',ed.base,qTokens,phrase));if(ed.sup)found.push(...candidates('editorial-supplement',ed.sup,qTokens,phrase));
  const pathHits=(ed.paths||[]).map(p=>({p,score:scoreText(p,qTokens,phrase)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,14);
  if(pathHits.length<6){for(const p of (ed.paths||[]).slice(0,6))if(!pathHits.some(x=>x.p===p))pathHits.push({p,score:1})}
  const batches=await Promise.all(pathHits.map(async x=>[x.p,await getJson(origin,'/'+x.p,2600000)]));
  for(const [path,data] of batches)if(data)found.push(...candidates('article:'+path,data,qTokens,phrase));
  found.sort((a,b)=>b.score-a.score);
  const unique=[];const seen=new Set();for(const f of found){const k=(f.title+'|'+snippet(f.text,qTokens,260)).toLowerCase();if(seen.has(k))continue;seen.add(k);unique.push(f);if(unique.length>=18)break}
  const bookCandidates=unique.filter(x=>x.label==='library'&&x.raw?.capabilities?.searchable&&x.raw?.localUrl).slice(0,3);
  for(const b of bookCandidates){const full=await getText(origin,b.raw.localUrl);if(!full)continue;const s=scoreText(full,qTokens,phrase);if(s>0)unique.unshift({score:b.score+s+20,label:'book-fulltext',title:b.title,route:b.raw.readerUrl||b.raw.localUrl,text:snippet(full,qTokens,3800),raw:b.raw})}
  const mediaCandidates=unique.filter(x=>x.label==='media').slice(0,4);for(const m of mediaCandidates){const r=m.raw||{};for(const key of ['transcriptUrl','captionUrl','captionsUrl','textUrl','localTranscript','transcript']){const p=r[key];if(typeof p==='string'&&p.startsWith('/')){const full=await getText(origin,p);if(full){const s=scoreText(full,qTokens,phrase);if(s>0)unique.unshift({score:m.score+s+20,label:'media-transcript',title:m.title,route:m.route,text:snippet(full,qTokens,3200),raw:r});break}}}}
  unique.sort((a,b)=>b.score-a.score);return unique.slice(0,10).map((x,i)=>({id:i+1,type:x.label,title:x.title,route:x.route,text:snippet(x.text,qTokens,x.label==='book-fulltext'?3800:2200),score:x.score}))}
export async function onRequestPost({request,env}){if(!env?.OPENAI_API_KEY)return json({error:'CHAT_NOT_CONFIGURED'},503);let body;try{body=await request.json()}catch{return json({error:'INVALID_JSON'},400)}const message=cleanString(body?.message,1800);if(!message)return json({error:'EMPTY_MESSAGE'},400);const lang=localeOf(body?.language);const L=LOCALE[lang];const history=Array.isArray(body?.history)?body.history.slice(-8).map(x=>({role:x?.role==='assistant'?'assistant':'user',text:cleanString(x?.text,1200)})).filter(x=>x.text):[];try{const mod=await openai('moderations',env.OPENAI_API_KEY,{model:'omni-moderation-latest',input:message});if(mod?.results?.[0]?.flagged)return json({answer:L.unsafe,grounded:false,language:lang});const current={title:cleanString(body?.context?.title,240),excerpt:cleanString(body?.context?.excerpt,12000)};const retrieved=await retrieveWholeSite(request,message,current);if(!retrieved.length)return json({answer:L.unsupported,grounded:false,language:lang,sources:[]});const transcript=history.map(x=>`${x.role}: ${x.text}`).join('\n');const corpus=retrieved.map(x=>`[SITE_SOURCE ${x.id}]\nTYPE: ${x.type}\nTITLE: ${x.title}\nROUTE: ${x.route||'-'}\nTEXT:\n${x.text}`).join('\n\n');const input=`RETRIEVED_SITE_CONTENT_BEGIN\n${corpus}\nRETRIEVED_SITE_CONTENT_END\n${transcript?`\nRECENT_GROUNDED_CHAT:\n${transcript}\n`:''}\nCHILD_QUESTION:\n${message}`;const response=await openai('responses',env.OPENAI_API_KEY,{model:env.OPENAI_CHAT_MODEL||'gpt-5.6-luna',store:false,instructions:systemFor(lang),input,max_output_tokens:650});let answer=textFromResponse(response)||L.unsupported;const outMod=await openai('moderations',env.OPENAI_API_KEY,{model:'omni-moderation-latest',input:answer});if(outMod?.results?.[0]?.flagged)answer=L.fallback;return json({answer,grounded:true,language:lang,sources:retrieved.map(x=>({type:x.type,title:x.title,route:x.route})),model:env.OPENAI_CHAT_MODEL||'gpt-5.6-luna'});}catch(err){console.error('children-chat',err?.message||err);return json({error:'CHAT_UPSTREAM_ERROR'},502)}}
export async function onRequest({request,env}){if(request.method==='POST')return onRequestPost({request,env});return json({error:'METHOD_NOT_ALLOWED'},405)}
