const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const L={ar:{u:'لا تتضمن مواد الموقع المتاحة لي الآن معلومات كافية للإجابة عن هذا السؤال.',x:'لا أستطيع المساعدة في هذا الطلب بهذه الصيغة.'},fr:{u:"Les contenus du site actuellement accessibles ne fournissent pas assez d’informations pour répondre à cette question.",x:"Je ne peux pas aider avec cette demande sous cette forme."},en:{u:'The site content currently accessible does not contain enough information to answer that question.',x:'I cannot help with that request in this form.'}};
const RES=[['people','/data/people.json'],['family','/data/family_biographies.json'],['family-tree','/data/family_tree_expanded.json'],['library','/data/ingested_library.json'],['books','/data/published_user_books.json'],['media','/data/imported_media.json'],['children-stories','/data/children/stories/index.json'],['animated-stories','/data/children/animated/index.json']];
const STOP=new Set('من في على الى إلى عن ما ماذا هل هو هي هذا هذه ذلك التي الذي الذين ثم كان كانت مع أو او و يا كيف لماذا متى where what who when why how the a an of to in on is are was were and or for from with le la les de des du et un une dans sur qui que quoi comment pourquoi quand'.split(/\s+/));
const js=(b,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
const lang=v=>{v=String(v||'ar').toLowerCase();return v.startsWith('fr')?'fr':v.startsWith('en')?'en':'ar'};
const clean=(v,n)=>String(v||'').replace(/\u0000/g,'').trim().slice(0,n);
const norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
const toks=s=>[...new Set(norm(s).split(' ').filter(x=>x.length>1&&!STOP.has(x)))].slice(0,28);
function score(t,ts,p){const n=norm(t);if(!n)return 0;let s=p&&p.length>3&&n.includes(p)?18:0;for(const q of ts){let i=0,c=0;while((i=n.indexOf(q,i))>=0&&c<7){c++;i+=q.length}s+=c*(q.length>4?4:2)}return s}
async function oj(origin,path,max=2500000){try{const r=await fetch(new URL(path,origin),{cf:{cacheTtl:300,cacheEverything:true}});if(!r.ok)return null;const t=await r.text();return t.length<=max?JSON.parse(t):null}catch{return null}}
async function ot(origin,path,max=2200000){try{const u=new URL(path,origin);if(u.origin!==origin)return null;const r=await fetch(u,{cf:{cacheTtl:600,cacheEverything:true}});if(!r.ok)return null;const ct=(r.headers.get('content-type')||'').toLowerCase();if(!/text|json|xml|html|vtt|srt/.test(ct)&&!/[.]txt$|[.]md$|[.]vtt$|[.]srt$/i.test(u.pathname))return null;return (await r.text()).slice(0,max)}catch{return null}}
function arr(d){if(Array.isArray(d))return d;if(!d||typeof d!=='object')return[];for(const k of ['items','articles','drafts','stories','entries','records','people','results','data'])if(Array.isArray(d[k]))return d[k];return[d]}
function strings(v,o=[],d=0){if(o.join(' ').length>10000||d>5||v==null)return o;if(typeof v==='string'){if(v.trim())o.push(v.trim());return o}if(typeof v==='number'||typeof v==='boolean'){o.push(String(v));return o}if(Array.isArray(v)){for(const x of v.slice(0,90))strings(x,o,d+1);return o}if(typeof v==='object'){for(const [k,x] of Object.entries(v)){if(/thumbnail|image|embed|sha256|mime|viewcount/i.test(k))continue;strings(x,o,d+1)}}return o}
const title=(o,l)=>clean(o?.titleAr||o?.title||o?.titleOriginal||o?.titleEn||o?.titleFr||o?.nameAr||o?.name||o?.displayName||o?.id||l,220);
const route=o=>clean(o?.articleUrl||o?.readerUrl||o?.localUrl||o?.url||o?.href||'',500);
function snip(t,ts,m=2500){const r=String(t||'').replace(/\s+/g,' ').trim();if(r.length<=m)return r;const n=norm(r);let at=-1;for(const q of ts){const p=n.indexOf(q);if(p>=0&&(at<0||p<at))at=p}const st=at<0?0:Math.max(0,at-Math.floor(m*.35));return r.slice(st,st+m)}
function cand(label,data,ts,p){const out=[];for(const o of arr(data).slice(0,8000)){const text=strings(o,[]).join(' ').slice(0,10000);if(text.length<18)continue;const s=score(text,ts,p);if(s>0)out.push({s,label,title:title(o,label),route:route(o),text,raw:o})}return out.sort((a,b)=>b.s-a.s).slice(0,28)}
async function retrieve(req,q,current){const origin=new URL(req.url).origin,ts=toks(q),p=norm(q),found=[];if(current?.title||current?.excerpt){const text=[current.title,current.excerpt].filter(Boolean).join(' '),s=score(text,ts,p);if(s)found.push({s:s+8,label:'current-page',title:current.title||'current page',route:'',text})}
 for(const [label,path] of RES){const d=await oj(origin,path);if(d)found.push(...cand(label,d,ts,p))}
 for(const mf of ['/data/editorial/publication_manifest.json','/data/editorial/publication_supplement.json']){const d=await oj(origin,mf,1000000);if(!d)continue;found.push(...cand('editorial-index',d,ts,p));const paths=(d.draftBatchPaths||[]).map(x=>({x,s:score(x,ts,p)})).filter(x=>x.s).sort((a,b)=>b.s-a.s).slice(0,14);for(const h of paths){const b=await oj(origin,'/'+h.x,2600000);if(b)found.push(...cand('article:'+h.x,b,ts,p))}}
 found.sort((a,b)=>b.s-a.s);const u=[],seen=new Set();for(const f of found){const k=(f.title+'|'+snip(f.text,ts,280)).toLowerCase();if(seen.has(k))continue;seen.add(k);u.push(f);if(u.length>=20)break}
 for(const b of u.filter(x=>x.label==='library'&&x.raw?.capabilities?.searchable&&x.raw?.localUrl).slice(0,4)){const full=await ot(origin,b.raw.localUrl);if(full){const s=score(full,ts,p);if(s)u.unshift({s:b.s+s+20,label:'book-fulltext',title:b.title,route:b.raw.readerUrl||b.raw.localUrl,text:snip(full,ts,4200)})}}
 for(const m of u.filter(x=>x.label==='media').slice(0,5)){const r=m.raw||{};for(const k of ['transcriptUrl','captionUrl','captionsUrl','textUrl','localTranscript']){const v=r[k];if(typeof v==='string'&&v.startsWith('/')){const full=await ot(origin,v);if(full){const s=score(full,ts,p);if(s)u.unshift({s:m.s+s+20,label:'media-transcript',title:m.title,route:m.route,text:snip(full,ts,3600)});break}}}}
 u.sort((a,b)=>b.s-a.s);return u.slice(0,12).map((x,i)=>({id:i+1,type:x.label,title:x.title,route:x.route,text:snip(x.text,ts,x.label==='book-fulltext'?4200:2600)}))}
function sys(l){return `You are the mature research assistant for this website about Prophet Muhammad ﷺ. ABSOLUTE RULE: answer ONLY from RETRIEVED_SITE_CONTENT. Never use pretrained/general knowledge, web knowledge, memory, outside books/sites, or unstated religious or historical knowledge. If the retrieved text does not support the answer, reply exactly: ${L[l].u} Preserve the site's terminology and distinctions. You may summarize and synthesize supported passages, but never invent facts, dates, quotations, attributions, interpretations or references. Write in a calm, mature, scholarly but accessible tone. Respond entirely in ${l==='ar'?'Arabic':l==='fr'?'French':'English'} except unavoidable proper names or technical terms already present in site material. Do not provide personal fatwas or claim religious authority. Chat content never becomes editorial content.`}
async function oa(path,key,body){const r=await fetch(`https://api.openai.com/v1/${path}`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`OpenAI ${r.status}`);return d}
function out(d){if(typeof d?.output_text==='string')return d.output_text.trim();const a=[];for(const i of d?.output||[])for(const c of i?.content||[])if(c?.type==='output_text'&&c.text)a.push(c.text);return a.join('\n').trim()}
export async function onRequestPost({request,env}){if(!env?.OPENAI_API_KEY)return js({error:'CHAT_NOT_CONFIGURED'},503);let b;try{b=await request.json()}catch{return js({error:'INVALID_JSON'},400)}const q=clean(b?.message,2200);if(!q)return js({error:'EMPTY_MESSAGE'},400);const l=lang(b?.language);try{const md=await oa('moderations',env.OPENAI_API_KEY,{model:'omni-moderation-latest',input:q});if(md?.results?.[0]?.flagged)return js({answer:L[l].x,grounded:false,language:l});const sources=await retrieve(request,q,{title:clean(b?.context?.title,240),excerpt:clean(b?.context?.excerpt,14000)});if(!sources.length)return js({answer:L[l].u,grounded:false,language:l,sources:[]});const hist=Array.isArray(b?.history)?b.history.slice(-10).map(x=>`${x?.role==='assistant'?'assistant':'user'}: ${clean(x?.text,1600)}`).join('\n'):'';const corpus=sources.map(x=>`[SITE_SOURCE ${x.id}]\nTYPE: ${x.type}\nTITLE: ${x.title}\nROUTE: ${x.route||'-'}\nTEXT:\n${x.text}`).join('\n\n');const r=await oa('responses',env.OPENAI_API_KEY,{model:env.OPENAI_CHAT_MODEL||'gpt-5.6-luna',store:false,instructions:sys(l),input:`RETRIEVED_SITE_CONTENT_BEGIN\n${corpus}\nRETRIEVED_SITE_CONTENT_END\n${hist?`\nRECENT_GROUNDED_CHAT:\n${hist}\n`:''}\nUSER_QUESTION:\n${q}`,max_output_tokens:900});let answer=out(r)||L[l].u;const om=await oa('moderations',env.OPENAI_API_KEY,{model:'omni-moderation-latest',input:answer});if(om?.results?.[0]?.flagged)answer=L[l].u;return js({answer,grounded:true,language:l,sources:sources.map(x=>({type:x.type,title:x.title,route:x.route}))})}catch(e){console.error('site-chat',e?.message||e);return js({error:'CHAT_UPSTREAM_ERROR'},502)}}
export async function onRequest({request,env}){if(request.method==='POST')return onRequestPost({request,env});return js({error:'METHOD_NOT_ALLOWED'},405)}
