#!/usr/bin/env python3
from __future__ import annotations
import json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
FORBIDDEN=[
 re.compile(r'اتجاه الصور الجديد'),re.compile(r'مول[َّ]?دة بالذكاء الاصطناعي'),re.compile(r'نموذج بصري للمراجعة'),
 re.compile(r'\bAI[- ]generated\b',re.I),re.compile(r'\bgenerated by AI\b',re.I),re.compile(r'\bprompt\b',re.I),
 re.compile(r'\bmodel output\b',re.I),re.compile(r'\bfor review\b',re.I)
]
PUBLIC_TEXT_EXT={'.html','.json'}
IGNORE_PREFIXES=('.git/','.github/','node_modules/','scripts/','tests/')

def iter_public_text_files():
    for p in ROOT.rglob('*'):
        if not p.is_file() or p.suffix.lower() not in PUBLIC_TEXT_EXT: continue
        rel=p.relative_to(ROOT).as_posix()
        if rel.startswith(IGNORE_PREFIXES): continue
        yield p,rel

def process_language_violations():
    hits=[]
    for p,rel in iter_public_text_files():
        try:text=p.read_text(encoding='utf-8',errors='ignore')
        except Exception:continue
        for rx in FORBIDDEN:
            if rx.search(text): hits.append((rel,rx.pattern))
    return hits

def source_refs(obj):
    if not isinstance(obj,dict): return []
    vals=[]
    for k in ('sourceRefs','sources','references','resourceRefs'):
        v=obj.get(k)
        if isinstance(v,list): vals.extend(v)
    return [x for x in vals if x]

def audit_json_record(obj,path,label='root'):
    issues=[]
    if isinstance(obj,list):
        for i,x in enumerate(obj): issues.extend(audit_json_record(x,path,f'{label}[{i}]'))
        return issues
    if not isinstance(obj,dict): return issues
    substantive=any(k in obj for k in ('paragraphs','scenes','body','textAr','textEn','textFr','quotation'))
    publication=str(obj.get('publicationStatus') or obj.get('status') or '').upper()
    publicish=publication in ('READY','PUBLISHED','PUBLIC') or obj.get('published') is True
    if substantive and publicish and not source_refs(obj):
        # Editorial drafts can carry refs at paragraph level.
        nested=[]
        for k in ('paragraphs','scenes'):
            if isinstance(obj.get(k),list): nested.extend(obj[k])
        if not nested or any(isinstance(x,dict) and not source_refs(x) for x in nested):
            issues.append((path,label,'published substantive record lacks complete sourceRefs'))
    for k,v in obj.items():
        if isinstance(v,(dict,list)): issues.extend(audit_json_record(v,path,f'{label}.{k}'))
    return issues

def provenance_violations():
    issues=[]
    roots=[ROOT/'data/editorial',ROOT/'data/children']
    for base in roots:
        if not base.exists(): continue
        for p in base.rglob('*.json'):
            try: obj=json.loads(p.read_text(encoding='utf-8'))
            except Exception: continue
            issues.extend(audit_json_record(obj,p.relative_to(ROOT).as_posix()))
    return issues

def main():
    process_hits=process_language_violations()
    provenance=provenance_violations()
    print('public process-language hits:',len(process_hits))
    for x in process_hits[:100]: print('PROCESS',*x,sep=' | ')
    print('published provenance violations:',len(provenance))
    for x in provenance[:200]: print('SOURCE',*x,sep=' | ')
    # Process-language violations are a hard failure now. Provenance violations are
    # reported as migration blockers so existing unsourced corpora are preserved
    # without silently treating them as compliant.
    if process_hits: return 1
    return 0
if __name__=='__main__': raise SystemExit(main())
