#!/usr/bin/env python3
# GOVERNED_BY: MASTER-OVERRIDING-SITE-INSTRUCTION.md
from __future__ import annotations
import json,re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

# Public pages/data must not expose implementation, model, review, prompt, or
# synthetic-content commentary. These are editorial/process concepts, not site content.
FORBIDDEN=[
    re.compile(r'اتجاه الصور الجديد'),
    re.compile(r'مول[َّ]?دة بالذكاء الاصطناعي'),
    re.compile(r'نموذج بصري للمراجعة'),
    re.compile(r'الذكاء الاصطناعي'),
    re.compile(r'\bAI[- ]generated\b',re.I),
    re.compile(r'\bgenerated by AI\b',re.I),
    re.compile(r'\bAI generated\b',re.I),
    re.compile(r'\bprompt\b',re.I),
    re.compile(r'\bmodel output\b',re.I),
    re.compile(r'\bfor review\b',re.I),
    re.compile(r'\bpreview for review\b',re.I),
]

PUBLIC_TEXT_EXT={'.html','.json'}
IGNORE_PREFIXES=('.git/','.github/','node_modules/','scripts/','tests/')

# Substantive public fields that must have resource provenance when a record is
# READY/PUBLISHED/PUBLIC. Public content may be quoted, excerpted, transcribed,
# translated, or conservatively edited, but the source relationship must remain explicit.
SUBSTANTIVE_KEYS={
    'paragraphs','scenes','body','content','text','textAr','textEn','textFr',
    'quotation','quote','transcript','summary','descriptionAr','descriptionEn','descriptionFr'
}
SOURCE_KEYS=('sourceRefs','sources','references','resourceRefs','sourceIds','resourceIds')
PUBLIC_STATUSES={'READY','PUBLISHED','PUBLIC'}


def iter_public_text_files():
    for p in ROOT.rglob('*'):
        if not p.is_file() or p.suffix.lower() not in PUBLIC_TEXT_EXT:
            continue
        rel=p.relative_to(ROOT).as_posix()
        if rel.startswith(IGNORE_PREFIXES):
            continue
        yield p,rel


def process_language_violations():
    hits=[]
    for p,rel in iter_public_text_files():
        try:
            text=p.read_text(encoding='utf-8',errors='ignore')
        except Exception:
            continue
        for rx in FORBIDDEN:
            if rx.search(text):
                hits.append((rel,rx.pattern))
    return hits


def source_refs(obj):
    if not isinstance(obj,dict):
        return []
    vals=[]
    for k in SOURCE_KEYS:
        v=obj.get(k)
        if isinstance(v,list):
            vals.extend(v)
        elif isinstance(v,(str,int)) and v:
            vals.append(v)
    return [x for x in vals if x]


def is_public_record(obj):
    if not isinstance(obj,dict):
        return False
    publication=str(obj.get('publicationStatus') or obj.get('status') or '').upper()
    return publication in PUBLIC_STATUSES or obj.get('published') is True


def is_substantive(obj):
    return isinstance(obj,dict) and any(k in obj for k in SUBSTANTIVE_KEYS)


def nested_content_nodes(obj):
    nodes=[]
    if not isinstance(obj,dict):
        return nodes
    for k in ('paragraphs','scenes','sections','items'):
        v=obj.get(k)
        if isinstance(v,list):
            nodes.extend(x for x in v if isinstance(x,dict))
    return nodes


def audit_json_record(obj,path,label='root',inherited_refs=None):
    issues=[]
    inherited_refs=list(inherited_refs or [])
    if isinstance(obj,list):
        for i,x in enumerate(obj):
            issues.extend(audit_json_record(x,path,f'{label}[{i}]',inherited_refs))
        return issues
    if not isinstance(obj,dict):
        return issues

    own_refs=source_refs(obj)
    effective_refs=own_refs or inherited_refs

    if is_public_record(obj) and is_substantive(obj):
        nodes=nested_content_nodes(obj)
        if not effective_refs:
            issues.append((path,label,'published substantive record lacks source/resource references'))
        if nodes:
            for i,node in enumerate(nodes):
                if is_substantive(node) and not (source_refs(node) or effective_refs):
                    issues.append((path,f'{label}.content[{i}]','published content node lacks source/resource references'))

    for k,v in obj.items():
        if isinstance(v,(dict,list)):
            issues.extend(audit_json_record(v,path,f'{label}.{k}',effective_refs))
    return issues


def provenance_violations():
    issues=[]
    roots=[ROOT/'data/editorial',ROOT/'data/children']
    for base in roots:
        if not base.exists():
            continue
        for p in base.rglob('*.json'):
            try:
                obj=json.loads(p.read_text(encoding='utf-8'))
            except Exception:
                continue
            issues.extend(audit_json_record(obj,p.relative_to(ROOT).as_posix()))
    return issues


def main():
    process_hits=process_language_violations()
    provenance=provenance_violations()

    print('public process-language hits:',len(process_hits))
    for x in process_hits[:200]:
        print('PROCESS',*x,sep=' | ')

    print('published provenance violations:',len(provenance))
    for x in provenance[:500]:
        print('SOURCE',*x,sep=' | ')

    # MASTER RULE: neither visible AI/process commentary nor unsourced public
    # substantive records may pass publication checks.
    return 1 if (process_hits or provenance) else 0


if __name__=='__main__':
    raise SystemExit(main())
